nyc_taxi_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'NYC_TAXI') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'NYC_TAXI_WH') }}"
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: false
