CREATE WAREHOUSE IF NOT EXISTS {{ warehouse }}
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS {{ database }};

CREATE SCHEMA IF NOT EXISTS {{ database }}.BRONZE;
CREATE SCHEMA IF NOT EXISTS {{ database }}.SILVER;
CREATE SCHEMA IF NOT EXISTS {{ database }}.GOLD;

CREATE FILE FORMAT IF NOT EXISTS {{ database }}.BRONZE.YELLOW_TAXI_PARQUET_FORMAT
    TYPE = PARQUET;

CREATE FILE FORMAT IF NOT EXISTS {{ database }}.BRONZE.TAXI_ZONE_CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL');

CREATE STAGE IF NOT EXISTS {{ database }}.BRONZE.YELLOW_TAXI_STAGE
    FILE_FORMAT = {{ database }}.BRONZE.YELLOW_TAXI_PARQUET_FORMAT;

CREATE STAGE IF NOT EXISTS {{ database }}.BRONZE.TAXI_ZONE_STAGE
    FILE_FORMAT = {{ database }}.BRONZE.TAXI_ZONE_CSV_FORMAT;

CREATE TABLE IF NOT EXISTS {{ database }}.BRONZE.RAW_YELLOW_TAXI (
    RAW_RECORD VARIANT NOT NULL,
    SOURCE_FILE VARCHAR NOT NULL,
    SOURCE_PERIOD VARCHAR(7) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS {{ database }}.BRONZE.RAW_TAXI_ZONE_LOOKUP (
    LOCATION_ID NUMBER,
    BOROUGH VARCHAR,
    ZONE VARCHAR,
    SERVICE_ZONE VARCHAR,
    SOURCE_FILE VARCHAR NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL
);
