select
    trip_key,
    coalesce(vendor_id, -1) as vendor_key,
    to_number(to_char(pickup_at::date, 'YYYYMMDD')) as pickup_date_key,
    date_part('hour', pickup_at) * 100 + date_part('minute', pickup_at) as pickup_time_key,
    to_number(to_char(dropoff_at::date, 'YYYYMMDD')) as dropoff_date_key,
    date_part('hour', dropoff_at) * 100 + date_part('minute', dropoff_at) as dropoff_time_key,
    pickup_location_id as pickup_location_key,
    dropoff_location_id as dropoff_location_key,
    coalesce(rate_code_id, -1) as rate_code_key,
    coalesce(payment_type_id, -1) as payment_type_key,
    passenger_count,
    trip_distance,
    datediff('second', pickup_at, dropoff_at) as trip_duration_seconds,
    fare_amount,
    extra_amount,
    mta_tax,
    tip_amount,
    tolls_amount,
    improvement_surcharge,
    total_amount,
    congestion_surcharge,
    airport_fee,
    cbd_congestion_fee,
    store_and_fwd_flag,
    source_file,
    source_period,
    loaded_at
from {{ ref('slv_yellow_taxi') }}
